[package]
name = "agora-rs-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0"
function_name = "0.3.0"
log = "0.4"
env_logger = "0.9.0"
agora-rtsa-rs = { path = "../rust-agora" }